---

- hosts: all
  become: true
  become_method: sudo
#  roles:
#    - common

- hosts: tag_app_mesosmaster
  tasks: []
  tags:
    - always

- hosts: tag_app_mesosslave
  tasks: []
  tags:
    - always

- hosts: tag_app_mesosmaster
  become: true
  roles:
    - mesos-common
    - mesos-master
  vars:
    # paas_apps_fqdn: 'paas.mozilla.community'
    paas_apps_fqdn: 'shadownet.buluma.me.ke'
  tags:
    - mesos-master

- hosts: tag_app_mesosslave
  become: true
  roles:
    - mesos-common
    - mesos-slave
  tags:
    - mesos-slave
